### ISSUE TITLE
My list of things to do

### ISSUE THREAD

**Issue by tekulvw** [tekulvw/Squid-Plugins#1]
- [x] ~MessageParser cog~
- [ ] Rate limit emotes
- [x] Document RSS 975cb97
- [ ] Hublinker should also share (optionally) cc's, aliases, modset, emotes
- [x] Scheduler, remove event from queue on remove
- [x] Karma toggle karma count on give/take 3ced6f0d

**Comment by irdumbs** [comment]
fix alias case sensitivity

**Comment by tekulvw** [comment]
Nixing this in the face of V3
