### ISSUE TITLE
another karma cog suggestion

### ISSUE THREAD

**Issue by ayshunstyle** [tekulvw/Squid-Plugins#12]
add a cooldown in between uses (like the slot machines from economy cog)

**Comment by tekulvw** [comment]
A cool down in between getting points?

**Comment by ayshunstyle** [comment]
a cooldown for each user before they can use ++ or -- again

**Comment by tekulvw** [comment]
I don't think I will, Karma was never intended to be something that is actually reliable. Just a fun thing designed to be abused by the Internet lol
