### ISSUE TITLE
(Suggestion) Descriptions of cogs on main repo page

### ISSUE THREAD

**Issue by The1stVoidRunner** [tekulvw/Squid-Plugins#2]
It would be very helpful if you added a tiny Description of what the cog does somewhere. (or am i just missing it and or blind?)

**Comment by tekulvw** [comment]
haha no you're not blind, there's nothing here when there really should be. I plan to start making them as soon as finals are over

**Comment by logoman** [comment]
Ah. Ok. Cool.

**Comment by The1stVoidRunner** [comment]
hey! I see you uploaded info.jsons. THX!

**Comment by The1stVoidRunner** [comment]
or... at least most of them

**Comment by tekulvw** [comment]
Hublinker is...special, and not complete. I'll add a warning on to it. Any other descriptions you'd like to see (besides a repo README)?

**Comment by The1stVoidRunner** [comment]
All of them have descriptions. Thats pretty much what I wanted.
