### ISSUE TITLE
RSS stops working after a few hours.

### ISSUE THREAD

**Issue by nikolaaa4** [tekulvw/Squid-Plugins#30]
After a few hours, or a day, the bot stops updating RSS feeds. Any reason for that?

**Comment by tekulvw** [comment]
Have not been able to replicate or seen any evidence of this occurring. Unless you can give me an error or a traceback there's not much I can do

**Comment by nikolaaa4** [comment]
Doesn't seem to be happening anymore, must've been my server.

**Comment by mining-d** [comment]
Use scheduler to repeat "reload RSS" every 1 hour

[p]scheduler repeat RSS 1h reload RSS
