### ISSUE TITLE
Hublinker problem

### ISSUE THREAD

**Issue by Spriter337** [tekulvw/Squid-Plugins#31]
Have been unable to use the hublinker as it says it requires the squid role to be above all other roles in all slave servers, but when that is the case I still get that message

**Comment by tekulvw** [comment]
Did you make a role named "Squid" and put it above all others with the necessary permissions (namely Administrator)?

**Comment by Spriter337** [comment]
yes I have

**Comment by tekulvw** [comment]
Well tbh, it works for me and was never actually meant for others use. Gonna close this.
