### ISSUE TITLE
Partycrash won't show a list when it hits more than 100 servers.

### ISSUE THREAD

**Issue by nikolaaa4** [tekulvw/Squid-Plugins#32]
When a bot hits 100 servers, partycrash won't show a list and therefore it's unusable.
My recommendation: Split the message every 100 servers.

**Comment by nikolaaa4** [comment]
Has an update been pushed out or something? There was no reply.

**Comment by tekulvw** [comment]
Nope.

![image](https://cloud.githubusercontent.com/assets/3731082/20907511/a942370e-bb1c-11e6-8eb6-59cc2f0cf5b7.png)
