### ISSUE TITLE
[suggestion] Permissions cog | A lock-like function but like a blacklist

### ISSUE THREAD

**Issue by Nathsters** [tekulvw/Squid-Plugins#34]
For the permissions cog I think it would be cool to have a command that automatically blacklists a command for everyone and in order for groups to use that command they have to be whitelisted. Unless there's already a way to do that just thought it would be cool and useful.

**Comment by tekulvw** [comment]
This is definitely already possible. All you need to do is `!p role deny @everyone <command>` then use `!p role allow <role_name> <command>` for each role you want to allow.
