### ISSUE TITLE
(SUGGESTION)/ (issue?)

### ISSUE THREAD

**Issue by Testdude3234** [tekulvw/Squid-Plugins#36]
For partycrash theres a limit of 100 servers or so before it claims it can't show the list.

I would like a few things changed.
First the servers cog or so can show more then 100 servers.

1. Allow more then 100 servers
2. If it's too much, A user can do *partycrash page 2 
etc

3. Allow the command to just *partycrash (servername) 
If it does already then it's broken.

**Comment by tekulvw** [comment]
Fixed with 65e3ced0
