### ISSUE TITLE
Announcement improvement

### ISSUE THREAD

**Issue by Mamalus** [tekulvw/Squid-Plugins#47]
Allow server admin/moderators to designate where the announcement goes. If not registered default is the general chat.
This will help other servers to know what updates that has been made to the bot because I do announcement when big changes that could affect them. Casino cog, new commands, deleted commands etc. General chat gets flooded which cause them to miss the bot announcement.
add another command to allow them to turn off the announcement if they don't want it.

**Comment by tekulvw** [comment]
Fixed in Red V3, will not be adding to V2.
