### ISSUE TITLE
botinfo.info command conflicts with existing info command from general.py

### ISSUE THREAD

**Issue by Canule** [tekulvw/Squid-Plugins#6]
It seems to raise a
NoSetupError:
Failed to load: cogs.general

botinfo.py@ln79

» Conflict avoided by renaming the command to 'infoz'

**Comment by tekulvw** [comment]
also `servers` conflicts with owner

**Comment by The1stVoidRunner** [comment]
getting the same issue.
Here is an image of the cmd if you need it: https://gyazo.com/05ca3beb46aaea5c42f4b3b39010fe61

**Comment by tekulvw** [comment]
Both conflicts are now fixed by me renaming `servers` to `servercount` and 26 renaming `info` to `userinfo`
