### ISSUE TITLE
Suggestion: Bigger Twitch Emotes?

### ISSUE THREAD

**Issue by Zelakto** [tekulvw/Squid-Plugins#8]
Is it possible to upload bigger emotes than just the standard Twitch sizes? Like size 3.0. This would be awesome, thank you for making this in the first place. :heart:

**Comment by tekulvw** [comment]
If there's a way to do this without another library import sure, if not, possibly. I'll look into it

**Comment by Decicus** [comment]
It's possible to accomplish using a different endpoint, which behaves similarly to the one currently used: `https://api.twitch.tv/kraken/chat/emoticon_images`

You can use the `id` value for each emote in this URL: `https://static-cdn.jtvnw.net/emoticons/v1/{EMOTE_ID}/{FORMAT}`, where `{FORMAT}` is either `1.0`, `2.0` or `3.0`.

**Comment by tekulvw** [comment]
Interesting...I'll probably add this in as an optional argument for the `emote` command

**Comment by tekulvw** [comment]
Added `!emoteset scale <number>` with a85da34d
